//create webserver  
// npm install express
// npm install body-parser
// npm install express-fileupload
// npm install ejs
// npm install mysql
// npm install mysql2
// npm install sequelize
// npm install sequelize-cli
// npm install bcrypt
// npm install express-session
// npm install nodemailer
// npm install sequelize-auto
// npm install sequelize-auto-fix
// npm install dotenv
// npm install passport
// npm install passport-local
// npm install connect-flash
// npm install express-flash
// npm install express-validator
// npm install cookie-parser
// npm install connect-mysql
// npm install express-myconnection
// npm install mysql
// npm install mysql2
// npm install sequelize
// npm install sequelize-cli
// npm install bcrypt
// npm install express-session
// npm install nodemailer
// npm install sequelize-auto
// npm install sequelize-auto-fix
// npm install dotenv
// npm install passport
// npm install passport-local
// npm install connect-flash
// npm install express-flash
// npm install express-validator
// npm install cookie-parser
// npm install connect-mysql
// npm install express-myconnection
// npm install mysql
// npm install mysql2
// npm install sequelize
// npm install sequelize-cli
// npm install bcrypt
// npm install express-session
// npm install nodemailer
// npm install sequelize-auto
// npm install sequelize-auto-fix
// npm install dotenv
// npm install passport
// npm install passport-local
// npm install connect-flash
// npm install express-flash
// npm install express-validator
// npm install cookie-parser
// npm install connect-mysql
// npm install express-myconnection
// npm install mysql
// npm install mysql2
// npm install sequelize
// npm install sequelize-cli
// npm install bcrypt
// npm install express-session
// npm install nodemailer
// npm install sequelize-auto
// npm install sequelize-auto-fix
// npm install dotenv
// npm install passport
// npm install passport-local
// npm install connect-flash
// npm install express-flash
// npm install express-validator
// npm install cookie-parser
// npm install connect-mysql
// npm install express-myconnection
// npm install mysql
// npm install mysql2
// npm install sequelize
// npm install sequelize-cli
// npm install bcrypt
// npm install express-session
// npm install nodemailer
// npm install sequelize-auto
// npm install sequelize-auto-fix
